language: python

python:
  - "3.5"

services:
    - postgresql

install:
    - make install
    - pip install coveralls

before_script:
    - psql -c "CREATE ROLE anonboard LOGIN PASSWORD 'anonboard';" -U postgres
    - psql -c "CREATE DATABASE test_anonboard;" -U postgres

script: make test

after_script: coveralls
