language: python

python:
  - "3.5"

services:
    - postgresql

install: make install

before_script:
    - psql -c "CREATE ROLE anonboard LOGIN PASSWORD 'anonboard';" -U postgres
    - psql -c "CREATE DATABASE test_anonboard;" -U postgres
    - make migrate

script: make test
