# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160322_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='comment',
            name='referenced',
            field=models.ManyToManyField(blank=True, null=True, to='core.Comment'),
        ),
    ]
