# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160410_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='referenced',
            field=models.ManyToManyField(blank=True, to='core.Comment'),
        ),
    ]
