# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160418_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.CharField(max_length=140),
        ),
    ]
